# Generated by Django 3.2.4 on 2022-02-13 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=2)),
                ('branch', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('COMP', 'Computer Engineering'), ('EL', 'Electrical Engineering'), ('ENTC', 'Electronics and Telecommunication Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('AI&DS', 'Artificial Intelligence & Data Science'), ('AR', 'Automation & Robotics')], default='COMP', max_length=5)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=2)),
                ('branch', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('COMP', 'Computer Engineering'), ('EL', 'Electrical Engineering'), ('ENTC', 'Electronics and Telecommunication Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('AI&DS', 'Artificial Intelligence & Data Science'), ('AR', 'Automation & Robotics')], default='COMP', max_length=5)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('roll_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=2)),
                ('branch', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('COMP', 'Computer Engineering'), ('EL', 'Electrical Engineering'), ('ENTC', 'Electronics and Telecommunication Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('AI&DS', 'Artificial Intelligence & Data Science'), ('AR', 'Automation & Robotics')], default='COMP', max_length=5)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('standard', 'branch', 'division')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=2)),
                ('branch', models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('COMP', 'Computer Engineering'), ('EL', 'Electrical Engineering'), ('ENTC', 'Electronics and Telecommunication Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('AI&DS', 'Artificial Intelligence & Data Science'), ('AR', 'Automation & Robotics')], default='COMP', max_length=5)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('roll_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('standard', 'branch', 'division', 'roll_no')},
            },
        ),
    ]
