# Generated by Django 3.2.4 on 2022-02-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-created',)},
        ),
    ]
