# Generated by Django 3.2.3 on 2021-06-03 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCQResponse',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='MCQ',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Record',
            new_name='Session',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='mcq',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
    ]
