# Generated by Django 3.2.3 on 2021-06-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210605_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='bookmarks',
            field=models.ManyToManyField(to='core.Question'),
        ),
    ]
