# Generated by Django 3.2.3 on 2021-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_session_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='active',
            field=models.BooleanField(help_text='UNCHECKING WILL SUBMIT ALL ONGOING SESSIONS OF THIS EXAM.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
