# Generated by Django 3.2.3 on 2021-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210615_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
