# Generated by Django 3.2.3 on 2021-06-17 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210615_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
