# Generated by Django 3.2.3 on 2021-06-24 10:47

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='marks_on_correct_answer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='marks_on_wrong_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='In format hh:mm:ss', validators=[core.models.validate_max_duration, core.models.validate_min_duration]),
        ),
    ]
