# Generated by Django 3.2.3 on 2021-06-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210624_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passing_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks_on_correct_answer',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks_on_wrong_answer',
            field=models.FloatField(default=0),
        ),
    ]
